@host=https://localhost:7005

POST {{host}}/auth/register HTTP/1.1
content-type: application/json

{
    "firstName": "Bob",
    "lastName": "Yuan",
    "email": "bob@gmail.com",
    "password": "123456"
}