@host=https://localhost:7005
@hostId=00000000-0000-0000-0000-000000000000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3Y2YyYTgzYy1jMGQ0LTQ1NTctOGZiNS1mZjYzZTM4ZGQ0NjciLCJqdGkiOiI1OTU0MGFiMi0yYjQxLTQ2ZjEtYmZmMi05ZjNjNzQ4MzNjNWQiLCJnaXZlbl9uYW1lIjoiQm9iIiwiZmFtaWx5X25hbWUiOiJZdWFuIiwiZXhwIjoxNjY5NzY1NzQ2LCJpc3MiOiJCdWJiZXJEaW5uZXIiLCJhdWQiOiJCdWJiZXJEaW5uZXIifQ.7B2lKk-nyWcPfVJ0IZPFVzAlNwIJCdxwxbempt0Z8wo

POST {{host}}/hosts/{{hostId}}/menu HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "hostId": "111",
    "name": "Yummy Menu",
    "description": "New Year menu",
    "sections": [
        {
            "name":"Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name":"Deep fried wings",
                    "description": "Deep fried chicken wings"
                }
            ]
        }
    ]
}