@host=https://localhost:7005
@hostId=c0000000-0000-0000-0000-960000000326
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMjU4M2U2OS1kNGNjLTRiM2EtYTdkOC03MjIzNjU4NDVmYjQiLCJqdGkiOiIyMjA3NTNjMC04NGI2LTQzN2ItYjYyOC04ZTQ1NzdmNWNiNzIiLCJnaXZlbl9uYW1lIjoiQm9iIiwiZmFtaWx5X25hbWUiOiJZdWFuIiwiZXhwIjoxNjY5OTM4NDczLCJpc3MiOiJCdWJiZXJEaW5uZXIiLCJhdWQiOiJCdWJiZXJEaW5uZXIifQ.C-Vwz87A9HOn1PFmWk4dBExe8XdZAlqjYyxDwR2GAUA

POST {{host}}/hosts/{{hostId}}/menu HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "hostId": "931b2368-0b49-4b6c-a7f2-e9c4c7e6c093",
    "name": "Yummy Menu",
    "description": "New Year menu",
    "sections": [
        {
            "name":"Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name":"Deep fried wings",
                    "description": "Deep fried chicken wings"
                }
            ]
        }
    ]
}