@host=https://localhost:7005

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjY5ZGRiMS0yNmQ3LTRlM2UtYjYwZS03MzBjMjdhMWYzODUiLCJqdGkiOiIxNGI2N2E5Ny1iYmM4LTRkZTItYTc3NS1mMGQ5ZDZhNmMwODUiLCJnaXZlbl9uYW1lIjoiQm9iIiwiZmFtaWx5X25hbWUiOiJZdWFuIiwiZXhwIjoxNjY0NDMwMDg5LCJpc3MiOiJCdWJiZXJEaW5uZXIiLCJhdWQiOiJCdWJiZXJEaW5uZXIifQ.iuba1YW88bChpK2FkwMbSsuYuR_5LfxrAFrKattaovU

GET {{host}}/dinner
Authorization: Bearer {{token}}