@host=https://localhost:7005

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMjJkNGMyNi1mNjk3LTQwMmItODNlZC0wZTk1NTdjNDU3ZmQiLCJqdGkiOiI4YTZjY2VlMy1mYTAwLTQyZmMtODFlZS02ZGQ0Yjg4OGQ3NzgiLCJnaXZlbl9uYW1lIjoiQm9iIiwiZmFtaWx5X25hbWUiOiJZdWFuIiwiZXhwIjoxNjY0MzExMzQ0LCJpc3MiOiJCdWJiZXJEaW5uZXIiLCJhdWQiOiJCdWJiZXJEaW5uZXIifQ.G_3xI2-p9ZzUOj8kQx3YtDasFbCwtPNWGUJMg08xIXE

GET {{host}}/dinner
Authorization: Bearer {{token}}